export const lessonTracks = [
  { type: 'terminology', label: 'Thuật ngữ chuyên ngành', icon: 'dictionary', eyebrow: 'Giao tiếp đúng thuật ngữ', description: 'Hiểu thuật ngữ trong ngữ cảnh công việc, cách dùng trong tài liệu và trao đổi kỹ thuật.', action: 'Khám phá thuật ngữ', focus: 'Tìm thuật ngữ trong bối cảnh và thử diễn đạt lại bằng tiếng Anh.', task: 'Chọn hai thuật ngữ trong bài và viết một câu tiếng Anh mô tả khi nào bạn dùng chúng ở nơi làm việc.', accent: 'teal' },
  { type: 'technical_reading', label: 'Đọc hiểu kỹ thuật', icon: 'article', eyebrow: 'Đọc để hiểu hệ thống', description: 'Luyện đọc đặc tả, tài liệu kiến trúc và bài viết kỹ thuật; nhận diện ý chính và chi tiết quan trọng.', action: 'Bắt đầu đọc', focus: 'Đọc tài liệu trước, sau đó tự trả lời câu hỏi kiểm tra hiểu.', task: 'Tóm tắt ý chính của tài liệu bằng hai câu tiếng Anh; trích một chi tiết kỹ thuật làm bằng chứng.', accent: 'blue' },
  { type: 'api_documentation', label: 'Tài liệu API', icon: 'api', eyebrow: 'Đọc như một lập trình viên', description: 'Phân tích endpoint, phương thức, xác thực, request, response và lỗi từ tài liệu API.', action: 'Phân tích API', focus: 'Xác định method, path, quyền truy cập, dữ liệu đầu vào và mã phản hồi.', task: 'Viết lại cách gọi API: method và path là gì, cần gửi gì, phản hồi thành công và lỗi ra sao?', accent: 'violet' },
  { type: 'system_design', label: 'System Design', icon: 'account_tree', eyebrow: 'Diễn đạt kiến trúc', description: 'Đọc sơ đồ, giải thích thành phần hệ thống và trình bày các đánh đổi thiết kế bằng tiếng Anh.', action: 'Phân tích thiết kế', focus: 'Nêu mục tiêu, các thành phần chính và lý do lựa chọn kiến trúc.', task: 'Giải thích vai trò của hai thành phần kiến trúc và một đánh đổi thiết kế bằng tiếng Anh.', accent: 'indigo' },
  { type: 'case_study', label: 'Case study thực tế', icon: 'work', eyebrow: 'Xử lý tình huống', description: 'Đọc bối cảnh dự án, xác định vấn đề và luyện đưa ra giải pháp trong môi trường làm việc.', action: 'Xử lý tình huống', focus: 'Đặt câu hỏi làm rõ, đề xuất cách xử lý và đối chiếu với gợi ý.', task: 'Viết câu hỏi làm rõ yêu cầu với stakeholder và một tiêu chí nghiệm thu đo được.', accent: 'amber' },
] as const;

export type LessonTrack = (typeof lessonTracks)[number];
export const lessonTrackByType = (type: string) => lessonTracks.find(track => track.type === type);
