import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/shared/api/api-client';
import { useTheme } from '../../src/shared/store/theme-context';
import { EmptyState, FeatureScreen, featureStyles as s } from '../../src/shared/ui/FeatureScreen';

type Choice = { id: string; code: string; name: string; description?: string };
export default function PathGeneratorScreen() {
  const router = useRouter(); const { colors } = useTheme(); const [step, setStep] = useState(1); const [questions, setQuestions] = useState<any[]>([]); const [domains, setDomains] = useState<Choice[]>([]); const [goals, setGoals] = useState<Choice[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [placement, setPlacement] = useState<any>(null); const [domainCode, setDomainCode] = useState(''); const [goalCode, setGoalCode] = useState(''); const [minutes, setMinutes] = useState(30); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.get<any>('/placement-test'), api.get<any>('/domains'), api.get<any>('/career-goals')]).then(([test, ds, gs]) => { setQuestions(test.data ?? []); setDomains(ds.data ?? ds ?? []); setGoals(gs.data ?? gs ?? []); }).catch(e => setError(e.message || 'Không thể tải dữ liệu.')).finally(() => setLoading(false)); }, []);
  const allAnswered = questions.length > 0 && questions.every(q => answers[q.id]); const selectedDomain = useMemo(() => domains.find(x => x.code === domainCode), [domains, domainCode]);
  const submit = async () => { setBusy(true); try { setPlacement(await api.post('/placement-test/submit', { answers: questions.map(q => ({ questionId: q.id, optionId: answers[q.id] })) })); setStep(2); setError(''); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const generate = async () => { if (!placement || !domainCode || !goalCode) return; setBusy(true); try { await api.post('/learner-profiles/me/complete-onboarding', { levelCode: placement.levelCode, domainCodes: [domainCode], careerGoalCode: goalCode, weeklyStudyTargetMinutes: minutes * 5 }); await api.post('/learning-paths/generate', { careerGoal: goalCode, currentLevel: placement.levelCode, minutesPerDay: minutes, generationMode: 'system' }); router.replace('/roadmap' as any); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const choice = (item: Choice, active: boolean, onPress: () => void) => <TouchableOpacity key={item.id} onPress={onPress} style={[s.card, { backgroundColor: active ? `${colors.primary}15` : colors.surface, borderColor: active ? colors.primary : colors.outlineVariant }]}><Text style={[s.cardTitle, { color: colors.onSurface }]}>{item.name}</Text>{item.description ? <Text style={[s.muted, { color: colors.onSurfaceVariant }]}>{item.description}</Text> : null}</TouchableOpacity>;
  return <FeatureScreen title="Tạo lộ trình" subtitle={`Bước ${step}/3`} loading={loading} error={loading ? error : ''}>
    {error ? <Text style={{ color: colors.error, marginBottom: 12 }}>{error}</Text> : null}
    {step === 1 ? <>{!questions.length ? <EmptyState icon="quiz" title="Chưa có Placement Test" detail="Cần xuất bản câu hỏi có topic placement trước khi tạo lộ trình." /> : questions.map((q, i) => <View key={q.id} style={[s.card, { backgroundColor: colors.surface, borderColor: colors.outlineVariant }]}><Text style={[s.cardTitle, { color: colors.onSurface }]}>{i + 1}. {q.prompt}</Text>{q.options.map((o: any) => <TouchableOpacity key={o.id} onPress={() => setAnswers(v => ({ ...v, [q.id]: o.id }))} style={[s.button, { alignItems: 'flex-start', borderWidth: 1, borderColor: answers[q.id] === o.id ? colors.primary : colors.outlineVariant, backgroundColor: answers[q.id] === o.id ? `${colors.primary}12` : colors.background, marginTop: 7 }]}><Text style={{ color: colors.onSurface }}>{o.key}. {o.text}</Text></TouchableOpacity>)}</View>)}<TouchableOpacity disabled={!allAnswered || busy} onPress={submit} style={[s.button, { backgroundColor: colors.primary, opacity: !allAnswered || busy ? .45 : 1 }]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={{ color: '#fff', fontWeight: '800' }}>Chấm Placement Test</Text>}</TouchableOpacity></> : null}
    {step === 2 ? <><Text style={[s.cardTitle, { color: colors.onSurface }]}>Kết quả: {placement?.levelName} ({placement?.percent}%)</Text><Text style={[s.muted, { color: colors.onSurfaceVariant, marginBottom: 14 }]}>Chọn lĩnh vực IT bạn muốn theo đuổi.</Text>{domains.map(x => choice(x, domainCode === x.code, () => setDomainCode(x.code)))}<TouchableOpacity disabled={!domainCode} onPress={() => setStep(3)} style={[s.button, { backgroundColor: colors.primary, opacity: domainCode ? 1 : .45 }]}><Text style={{ color: '#fff', fontWeight: '800' }}>Tiếp tục</Text></TouchableOpacity></> : null}
    {step === 3 ? <><Text style={[s.cardTitle, { color: colors.onSurface }]}>Mục tiêu nghề nghiệp</Text><Text style={[s.muted, { color: colors.onSurfaceVariant, marginBottom: 12 }]}>{placement?.levelName} · {selectedDomain?.name}</Text>{goals.map(x => choice(x, goalCode === x.code, () => setGoalCode(x.code)))}<Text style={[s.cardTitle, { color: colors.onSurface, marginTop: 6 }]}>Thời gian mỗi ngày: {minutes} phút</Text><View style={[s.row, { flexWrap: 'wrap', marginBottom: 14 }]}>{[15, 30, 45, 60, 90, 120].map(x => <TouchableOpacity key={x} onPress={() => setMinutes(x)} style={[s.chip, { backgroundColor: minutes === x ? colors.primary : colors.surface }]}><Text style={{ color: minutes === x ? '#fff' : colors.onSurface }}>{x}</Text></TouchableOpacity>)}</View><TouchableOpacity disabled={!goalCode || busy} onPress={generate} style={[s.button, { backgroundColor: colors.primary, opacity: !goalCode || busy ? .45 : 1 }]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={{ color: '#fff', fontWeight: '800' }}>Tạo Personal Roadmap</Text>}</TouchableOpacity></> : null}
  </FeatureScreen>;
}
