import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { View } from 'react-native';
import { api } from '../../src/shared/api/api-client';
import { FeatureScreen } from '../../src/shared/ui/FeatureScreen';
import { Text, ListTools, Button, controlStyles } from '../../src/shared/ui/primitives';
export default function History() {
 const router = useRouter(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all');
 const load = useCallback(async () => { setLoading(true); try { const progress = await api.get<any>('/progress/me'); const records = progress.history ?? progress.progress ?? []; const lessons = await Promise.all(records.filter((item: any) => item.resourceType === 'lesson' && !item.lesson).map(async (item: any) => { try { return await api.get<any>(`/lessons/${item.resourceId}`); } catch { return null; } })); const map = new Map(lessons.filter(Boolean).map((lesson: any) => [lesson.id, lesson])); setItems(records.map((item: any) => ({ ...item, lesson: item.lesson || map.get(item.resourceId), lessonId: item.resourceType === 'lesson' ? item.resourceId : undefined, status: item.completionPercent >= 100 ? 'completed' : item.status }))); setError(''); } catch (cause: any) { setError(cause.message); } finally { setLoading(false); } }, []);
 useFocusEffect(useCallback(() => { void load(); }, [load]));
 const filtered = items.filter(item => (status === 'all' || item.status === status) && `${item.lesson?.title || item.lessonTitle || ''}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
 return <FeatureScreen title="Lịch sử học tập" loading={loading} error={error} onRetry={load}><ListTools search={query} onSearch={setQuery} placeholder="Tìm bài đã học" filters={[{ value: 'all', label: 'Tất cả' }, { value: 'completed', label: 'Hoàn thành' }, { value: 'in_progress', label: 'Đang học' }]} value={status} onFilter={setStatus}/>{filtered.map((item, index) => <View key={item.id || index} style={[controlStyles.card, { marginBottom: 12, gap: 8 }]}><Text style={{ fontWeight: '700' }}>{item.lesson?.title || item.lessonTitle || 'Bài học'}</Text><Text>{item.status === 'completed' ? 'Hoàn thành' : 'Đang học'}</Text><Text>{item.updatedAt || item.completedAt || item.startedAt ? new Date(item.updatedAt || item.completedAt || item.startedAt).toLocaleDateString('vi-VN') : ''}</Text>{(item.lessonId || item.lesson?.id) && <View style={controlStyles.footer}><Button onPress={() => router.push(`/lessons/${item.lessonId || item.lesson.id}` as any)}>Mở bài học</Button></View>}</View>)}{!filtered.length && <Text>Chưa có lịch sử phù hợp.</Text>}</FeatureScreen>;
}
