import { useEffect, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { View } from 'react-native';
import * as Speech from 'expo-speech';
import { api } from '../../src/shared/api/api-client';
import { FeatureScreen } from '../../src/shared/ui/FeatureScreen';
import { Text, Button, TextInput, controlStyles } from '../../src/shared/ui/primitives';
export default function Words() {
 const params = useLocalSearchParams<{ domainCode?: string; levelCode?: string; sourceLessonId?: string }>(); const router = useRouter(); const [words, setWords] = useState<any[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
 const load = async () => { setLoading(true); try { const qs = new URLSearchParams({status:'published',limit:'20',page:String(page),search}); if(params.domainCode)qs.set('domainCode',params.domainCode); if(params.levelCode)qs.set('levelCode',params.levelCode); if(params.sourceLessonId)qs.set('sourceLessonId',params.sourceLessonId); const result = await api.get<any>(`/vocabulary?${qs}`); setWords(result.data ?? []); setPages(Math.max(1,result.meta?.totalPages ?? 1)); setError(''); } catch(cause:any){setError(cause.message);} finally{setLoading(false);} };
 useEffect(()=>{void load()},[params.domainCode,params.levelCode,params.sourceLessonId,page,search]);
 return <FeatureScreen title="Danh sách từ vựng" loading={false} error={error} onRetry={load}><View style={{gap:12}}><View style={{flexDirection:'row',gap:8}}><TextInput accessibilityLabel="Tìm từ vựng" value={query} onChangeText={setQuery} placeholder="Tìm từ vựng" style={{flex:1,minWidth:0}}/><Button onPress={()=>{setSearch(query);setPage(1)}}>Tìm</Button></View><View style={controlStyles.footer}><Button onPress={()=>router.push({pathname:'/flashcards',params:{domainCode:params.domainCode,levelCode:params.levelCode,sourceLessonId:params.sourceLessonId}} as any)}>Học từ vựng</Button></View>{loading ? <Text>Đang tải…</Text> : words.map(word=><View key={word.id} style={[controlStyles.card,{gap:8}]}><Text style={{fontWeight:'700',fontSize:18}}>{word.term}</Text><Text>{word.pronunciationIpa}</Text><Text>{word.definitionVi}</Text><Text selectable>{word.definitionEn}</Text><View style={controlStyles.footer}><Button onPress={()=>{Speech.stop();Speech.speak(word.term,{language:'en-US'});}}>Phát âm</Button></View></View>)}{!loading&&!words.length&&<Text>Không có từ phù hợp.</Text>}<View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Button disabled={loading||page<=1} onPress={()=>setPage(value=>value-1)}>Trước</Button><Text>{page}/{pages}</Text><Button disabled={loading||page>=pages} onPress={()=>setPage(value=>value+1)}>Sau</Button></View></View></FeatureScreen>;
}
