import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Text, TouchableOpacity } from '../../src/shared/ui/primitives';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, View } from 'react-native';
import { MaterialIcons } from '../../src/shared/ui/AppIcon';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/shared/api/api-client';
import { LessonExperience } from '../../src/features/lessons/LessonExperience';
export default function LessonDetail(){
 const insets = useSafeAreaInsets();
 const {id}=useLocalSearchParams<{id:string}>(); const router=useRouter(); const [lesson,setLesson]=useState<any>(); const [completed,setCompleted]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [item,progress]=await Promise.all([api.get<any>(`/lessons/${id}`),api.get<any>('/progress/me')]);setLesson(item.data??item);const list=progress.data??progress.progress??progress??[];setCompleted(Array.isArray(list)&&list.some((x:any)=>x.resourceType==='lesson'&&x.resourceId===id&&x.status==='completed'));}catch(e:any){setError(e.message??'Không thể tải bài học');}finally{setLoading(false)}};
 useEffect(()=>{if(id)void load()},[id]);
 const finish=async()=>{setSaving(true);try{await api.post('/progress/me',{resourceType:'lesson',resourceId:id,status:'completed',completionPercent:100});setCompleted(true);Alert.alert('Hoàn thành','Tiến độ bài học đã được ghi nhận.');}catch(e:any){Alert.alert('Không thể cập nhật',e.message??'Vui lòng thử lại.');}finally{setSaving(false)}};
 if(loading)return <View style={s.center}><ActivityIndicator color="#3525cd"/></View>; if(error||!lesson)return <View style={s.center}><Text style={s.error}>{error||'Không tìm thấy bài học'}</Text><TouchableOpacity onPress={()=>void load()}><Text style={s.link}>Thử lại</Text></TouchableOpacity></View>;
 return <View style={[s.root, { paddingTop: insets.top }]}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-back" size={24}/></TouchableOpacity><Text numberOfLines={1} style={s.headerTitle}>{lesson.domain?.name??'Bài học'}</Text><View style={{width:24}}/></View><ScrollView contentContainerStyle={s.content}><Text style={{ color: '#464555', fontSize: 12, marginBottom: 12 }}>Nhấn giữ đoạn tiếng Anh để dịch theo ngữ cảnh.</Text><LessonExperience lesson={lesson}/></ScrollView><View style={[s.bottom, { paddingBottom: insets.bottom + 16 }]}><TouchableOpacity disabled={completed||saving} onPress={()=>void finish()} style={[s.button,completed&&s.done]}><MaterialIcons name="check-circle" size={20} color="#fff"/><Text style={s.buttonText}>{saving?'Đang lưu...':completed?'Đã hoàn thành':'Đánh dấu hoàn thành'}</Text></TouchableOpacity></View></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f9fb',paddingTop:46},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:20},header:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:'#e2e8f0',backgroundColor:'#fff'},headerTitle:{fontWeight:'700',fontSize:16,maxWidth:'75%'},content:{padding:16,paddingBottom:110},bottom:{position:'absolute',left:0,right:0,bottom:0,padding:16,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e2e8f0'},button:{height:50,borderRadius:13,backgroundColor:'#3525cd',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},done:{backgroundColor:'#15803d'},buttonText:{color:'#fff',fontWeight:'800'},error:{color:'#b91c1c',textAlign:'center'},link:{color:'#3525cd',fontWeight:'700',marginTop:12}});
