import { Text, TextInput, TouchableOpacity } from '../../src/shared/ui/primitives';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LearningActivities } from '../../src/features/learning/LearningActivities';
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, View } from 'react-native';
import { MaterialIcons } from '../../src/shared/ui/AppIcon';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/shared/api/api-client';

const TYPES: Record<string, { label: string; detail: string; action: string; icon: keyof typeof MaterialIcons.glyphMap }> = {
  terminology: { label: 'Thuật ngữ chuyên ngành', detail: 'Định nghĩa, ngữ cảnh và cách dùng', action: 'Khám phá thuật ngữ', icon: 'translate' },
  technical_reading: { label: 'Đọc hiểu kỹ thuật', detail: 'Tài liệu, ý chính và câu hỏi đọc hiểu', action: 'Bắt đầu đọc', icon: 'article' },
  api_documentation: { label: 'Tài liệu API', detail: 'Endpoint, request, response và lỗi', action: 'Phân tích API', icon: 'api' },
  system_design: { label: 'System Design', detail: 'Yêu cầu, kiến trúc và đánh đổi', action: 'Phân tích thiết kế', icon: 'account-tree' },
  case_study: { label: 'Case study thực tế', detail: 'Bối cảnh, nhiệm vụ và giải pháp', action: 'Xử lý tình huống', icon: 'work' },
};
export default function LessonList({ embedded = false }: { embedded?: boolean }) {
  const insets = useSafeAreaInsets();
  const router = useRouter(); const params = useLocalSearchParams<{domainCode?: string; type?: string}>();
  const [items,setItems]=useState<any[]>([]); const [query,setQuery]=useState(''); const [type,setType]=useState(params.type && TYPES[params.type] ? params.type : ''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(() => { setType(params.type && TYPES[params.type] ? params.type : ''); }, [params.type]);
  const load=async()=>{setLoading(true);setError('');try{const results=await Promise.all(Object.keys(TYPES).map(async lessonType=>{const qs=new URLSearchParams({limit:'100',status:'published',type:lessonType});if(params.domainCode)qs.set('domainCode',params.domainCode);const r=await api.get<any>(`/lessons?${qs}`);return r.data??r??[];}));setItems(results.flat());}catch(e:any){setError(e.message??'Không thể tải bài học');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[params.domainCode]);
  const filtered=useMemo(()=>items.filter(x=>TYPES[x.type]&&(!type||x.type===type)&&(!query.trim()||`${x.title} ${x.summary} ${x.domain?.name ?? ''} ${x.keyConcepts?.join(' ') ?? ''}`.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi')))),[items,query,type]);
  return <View style={[s.root, { paddingTop: insets.top }]}><View style={s.header}>{!embedded && <TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-back" size={24}/></TouchableOpacity>}<Text style={s.heading}>{type ? TYPES[type].label : 'Bài học'}</Text><View style={{width:24}}/></View><View style={s.search}><MaterialIcons name="search" size={20} color="#64748b"/><TextInput value={query} onChangeText={setQuery} placeholder="Tìm theo chủ đề, lĩnh vực..." style={{flex:1}}/></View><ScrollView style={{ flexGrow: 0, flexShrink: 0 }} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><TouchableOpacity onPress={()=>setType('')} style={[s.chip,!type&&s.active]}><Text style={!type?s.activeText:undefined}>Tất cả chuyên đề</Text></TouchableOpacity>{Object.entries(TYPES).map(([v,l])=><TouchableOpacity key={v} onPress={()=>setType(v)} style={[s.chip,type===v&&s.active]}><Text style={type===v?s.activeText:undefined}>{l.label}</Text></TouchableOpacity>)}</ScrollView>{loading?<ActivityIndicator style={{marginTop:50}} color="#3525cd"/>:error?<View style={s.center}><Text style={s.error}>{error}</Text><TouchableOpacity onPress={()=>void load()} style={s.retry}><Text style={s.activeText}>Thử lại</Text></TouchableOpacity></View>:<ScrollView contentContainerStyle={s.list}>{!type && <LearningActivities />}<View style={s.sectionHeader}><Text style={s.sectionTitle}>{type ? TYPES[type].label : 'Tất cả bài học chuyên ngành'}</Text><Text style={s.meta}>{filtered.length} bài phù hợp</Text></View>{type&&<Text style={s.trackDetail}>{TYPES[type].detail}</Text>}{filtered.map(x=><TouchableOpacity key={x.id} style={s.card} onPress={()=>router.push(`/lessons/${x.id}` as any)}><View style={s.icon}><MaterialIcons name={TYPES[x.type].icon} size={24} color="#3525cd"/></View><View style={{flex:1}}><Text style={s.title}>{x.title}</Text><Text numberOfLines={2} style={s.meta}>{TYPES[x.type].label} · {x.level?.name} · {x.estimatedMinutes} phút</Text><Text numberOfLines={2} style={s.summary}>{x.summary}</Text>{x.keyConcepts?.length > 0 && <View style={s.concepts}>{x.keyConcepts.slice(0, 3).map((concept: string, index: number) => <Text key={`${index}-${concept}`} style={s.concept}>{concept}</Text>)}</View>}<Text style={s.meta}>{x.domain?.name || 'Chuyên ngành CNTT'}</Text><Text style={s.action}>{TYPES[x.type].action} →</Text></View></TouchableOpacity>)}{!filtered.length&&<Text style={s.empty}>Không có nội dung phù hợp.</Text>}</ScrollView>}</View>;
}
const s=StyleSheet.create({sectionTitle:{fontSize:18,fontWeight:'700',color:'#191c1e',marginTop:12},sectionHeader:{gap:4},concepts:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},concept:{fontSize:11,color:'#464555',backgroundColor:'#f2f4f6',paddingHorizontal:7,paddingVertical:4,borderRadius:6},root:{flex:1,backgroundColor:'#f7f9fb',paddingTop:48},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:16},heading:{fontSize:20,fontWeight:'700',color:'#111827'},search:{marginHorizontal:16,flexDirection:'row',gap:8,alignItems:'center',backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:12,paddingHorizontal:12,height:46},chips:{gap:8,padding:16,alignItems:'center'},chip:{minHeight:44,justifyContent:'center',paddingHorizontal:14,paddingVertical:8,borderRadius:12,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0'},active:{backgroundColor:'#3525cd'},activeText:{color:'#fff',fontWeight:'700'},list:{padding:16,paddingTop:0,gap:12,paddingBottom:80},trackDetail:{fontSize:14,color:'#475569',padding:14,backgroundColor:'#eef2ff',borderRadius:12},card:{flexDirection:'row',alignItems:'flex-start',gap:12,backgroundColor:'#fff',padding:16,borderRadius:16,borderWidth:1,borderColor:'#e2e8f0'},icon:{width:46,height:46,borderRadius:12,backgroundColor:'#eef2ff',alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'700',color:'#111827'},meta:{fontSize:12,color:'#3525cd',marginTop:3},summary:{fontSize:13,color:'#64748b',marginTop:5,lineHeight:18},action:{fontSize:13,color:'#3525cd',fontWeight:'700',marginTop:10},center:{alignItems:'center',marginTop:50,gap:14},error:{color:'#b91c1c'},retry:{backgroundColor:'#3525cd',paddingHorizontal:18,paddingVertical:10,borderRadius:10},empty:{textAlign:'center',color:'#64748b',marginTop:40}});
