import { Fragment, type HTMLAttributes, type ReactNode } from 'react';
import { AlarmClock, Archive, ArrowDown, ArrowDownAZ, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, Award, Badge, BadgeCheck, Bell, BicepsFlexed, BookA, BookOpen, Bookmark, Brain, BriefcaseBusiness, CalendarDays, ChartColumn, ChartNoAxesColumn, ChartNoAxesColumnIncreasing, ChartNoAxesCombined, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, CircleAlert, CircleCheck, CircleDot, CircleHelp, CirclePlay, CircleX, ClipboardCheck, ClipboardList, Clock, Cloud, CloudUpload, Code2, Compass, Crop, Database, Diamond, Download, Ellipsis, EllipsisVertical, Eye, EyeOff, FastForward, FileDown, FilePenLine, FilePlus2, FileText, FileUp, FilterX, Flag, Flame, FolderOpen, Frown, Gamepad2, Globe, GraduationCap, Hand, History, House, Info, KeyRound, Languages, Laptop, Layers, LayoutDashboard, Library, Lightbulb, List, ListFilter, ListX, LoaderCircle, LockKeyhole, LockKeyholeOpen, LogOut, Mail, MailCheck, Medal, Meh, Menu, Network, PanelLeftClose, PartyPopper, Pencil, Plus, RefreshCw, Rocket, RotateCcw, Route, Save, Search, SearchX, Send, Settings, Shield, ShieldCheck, Siren, Smartphone, Smile, Sparkles, Square, SquareCheck, SquareTerminal, Star, Table, Target, Timer, ToggleRight, Trash2, TrendingUp, TriangleAlert, Trophy, Type, Upload, UserCog, UserRound, UserRoundMinus, UserRoundPlus, UserRoundSearch, UserRoundX, Users, Volume2, Webhook, X, Zap, ZoomIn, CirclePlus, Folder, MonitorSmartphone, Boxes, Scale, SquarePen, type LucideIcon } from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_right: ChevronRight,
  folder: Folder,
  highlight_off: CircleX,
  radio_button_unchecked: Circle,
  devices: MonitorSmartphone,
  deployed_code: Boxes,
  balance: Scale,
  edit_square: SquarePen,
  add_circle: CirclePlus,
  "account_tree": Network,
  "add": Plus,
  "admin_panel_settings": ShieldCheck,
  "alarm": AlarmClock,
  "analytics": ChartNoAxesCombined,
  "api": Webhook,
  "archive": Archive,
  "arrow_back": ArrowLeft,
  "arrow_forward": ArrowRight,
  "article": FileText,
  "assignment": ClipboardList,
  "assignment_turned_in": ClipboardCheck,
  "auto_stories": BookOpen,
  "badge": Badge,
  "bookmark": Bookmark,
  "cancel": CircleX,
  "check": Check,
  "check_box": SquareCheck,
  "check_box_outline_blank": Square,
  "check_circle": CircleCheck,
  "chevron_left": ChevronLeft,
  "chevron_right": ChevronRight,
  "close": X,
  "cloud_upload": CloudUpload,
  "code": Code2,
  "crop": Crop,
  "dashboard": LayoutDashboard,
  "delete": Trash2,
  "delete_forever": Trash2,
  "delete_sweep": ListX,
  "description": FileText,
  "diamond": Diamond,
  "dictionary": BookA,
  "download": Download,
  "edit": Pencil,
  "edit_note": FilePenLine,
  "error": CircleAlert,
  "expand_more": ChevronDown,
  "explore": Compass,
  "fact_check": ClipboardCheck,
  "fast_forward": FastForward,
  "file_download": FileDown,
  "filter_alt_off": FilterX,
  "filter_list_off": ListFilter,
  "folder_open": FolderOpen,
  "font_download": Type,
  "grade": Star,
  "group": Users,
  "groups": Users,
  "help": CircleHelp,
  "history": History,
  "home": House,
  "info": Info,
  "insights": ChartNoAxesCombined,
  "key": KeyRound,
  "leaderboard": ChartColumn,
  "library_books": Library,
  "local_fire_department": Flame,
  "lock": LockKeyhole,
  "lock_open": LockKeyholeOpen,
  "lock_reset": KeyRound,
  "logout": LogOut,
  "mail": Mail,
  "manage_accounts": UserCog,
  "mark_email_read": MailCheck,
  "menu": Menu,
  "menu_book": BookOpen,
  "menu_open": PanelLeftClose,
  "monitoring": ChartNoAxesCombined,
  "more_horiz": Ellipsis,
  "more_vert": EllipsisVertical,
  "people": Users,
  "person": UserRound,
  "person_add": UserRoundPlus,
  "person_off": UserRoundX,
  "person_remove": UserRoundMinus,
  "person_search": UserRoundSearch,
  "phone_iphone": Smartphone,
  "play_circle": CirclePlay,
  "post_add": FilePlus2,
  "progress_activity": LoaderCircle,
  "psychology": Brain,
  "publish": Upload,
  "quiz": ClipboardList,
  "radio_button_checked": CircleDot,
  "replay": RotateCcw,
  "route": Route,
  "save": Save,
  "school": GraduationCap,
  "search": Search,
  "search_off": SearchX,
  "send": Send,
  "sentiment_dissatisfied": Frown,
  "sentiment_neutral": Meh,
  "sentiment_satisfied": Smile,
  "settings": Settings,
  "shield": Shield,
  "shield_person": ShieldCheck,
  "signal_cellular_alt": ChartNoAxesColumnIncreasing,
  "signal_cellular_alt_1_bar": ChartNoAxesColumn,
  "signal_cellular_alt_2_bar": ChartNoAxesColumnIncreasing,
  "sort_by_alpha": ArrowDownAZ,
  "stairs": ChartNoAxesColumnIncreasing,
  "style": Layers,
  "sync": RefreshCw,
  "table_view": Table,
  "target": Target,
  "task_alt": CircleCheck,
  "terminal": SquareTerminal,
  "timer": Timer,
  "toggle_on": ToggleRight,
  "translate": Languages,
  "trending_up": TrendingUp,
  "upload_file": FileUp,
  "verified": BadgeCheck,
  "view_list": List,
  "visibility": Eye,
  "visibility_off": EyeOff,
  "volume_up": Volume2,
  "vpn_key": KeyRound,
  "warning": TriangleAlert,
  "work": BriefcaseBusiness,
  "work_outline": BriefcaseBusiness,
  "workspace_premium": Award,
  "zoom_in": ZoomIn,
  "cloud": Cloud,
  "database": Database,
  "network": Network,
  "chart-bar": ChartColumn,
  "loop": RefreshCw,
  "check_circle_outline": CircleCheck,
  "expand_less": ChevronUp,
  "arrow_drop_down": ChevronDown,
  "star": Star,
  "notifications": Bell,
  "language": Globe,
  "refresh": RefreshCw,
  "lightbulb": Lightbulb,
  "💡": Lightbulb,
  "⚠": TriangleAlert,
  "🎉": PartyPopper,
  "💪": BicepsFlexed,
  "📚": Library,
  "⚡": Zap,
  "🔥": Flame,
  "🎮": Gamepad2,
  "🏆": Trophy,
  "🧠": Brain,
  "🎓": GraduationCap,
  "💻": Laptop,
  "🗓": CalendarDays,
  "🚩": Flag,
  "🔔": Bell,
  "⚙": Settings,
  "✨": Sparkles,
  "🚨": Siren,
  "🎯": Target,
  "🚀": Rocket,
  "🏅": Medal,
  "➡": ArrowRight,
  "📋": ClipboardList,
  "🕘": Clock,
  "👋": Hand,
  "✓": Check,
  "✔": Check,
  "✕": X,
  "✖": X,
  "✗": X,
  "→": ArrowRight,
  "←": ArrowLeft,
  "↗": ArrowUpRight,
  "↓": ArrowDown,
  "↑": ArrowUp,
  "★": Star,
  "☆": Star,
  "●": Circle,
  "○": Circle,
  "×": X,
};

/** Render legacy/API icon identifiers through the single Lucide icon library. */
export function AppIcon({ children, className = '', style, ...props }: HTMLAttributes<HTMLSpanElement>) {
  const name = (Array.isArray(children) ? children.join('') : typeof children === 'string' ? children : '').trim().replace(/\uFE0F/g, '');
  const Icon = icons[name] ?? CircleHelp;
  return <span {...props} aria-hidden="true" className={`app-icon ${className}`} style={{ fontSize: className.match(/(?:^|\s)!?text-(?:\[|xs|sm|base|lg|xl|[2-9]xl)/) ? undefined : 24, ...style }}><Icon width="1em" height="1em" strokeWidth={2} /></span>;
}

/** Preserve labels that contain decorative symbols without displaying Unicode icons. */
export function IconText({ children }: { children: ReactNode }) {
  if (typeof children !== 'string') return <>{children}</>;
  const pattern = /(\p{Extended_Pictographic}\uFE0F?|[✓✔✕✖✗→←↗↓↑★☆●○])/gu;
  return <>{children.split(pattern).map((part, index) => icons[part.replace(/\uFE0F/g, '')]
    ? <AppIcon key={index} className="!text-[1em] align-middle">{part}</AppIcon>
    : <Fragment key={index}>{part}</Fragment>)}</>;
}
