ALTER TABLE "landing_banners"
ADD COLUMN "text_x" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN "text_y" DOUBLE PRECISION NOT NULL DEFAULT 18,
ADD COLUMN "text_width" DOUBLE PRECISION NOT NULL DEFAULT 46,
ADD COLUMN "text_align" VARCHAR(10) NOT NULL DEFAULT 'left',
ADD COLUMN "title_color" VARCHAR(20) NOT NULL DEFAULT '#0F172A',
ADD COLUMN "title_size" INTEGER NOT NULL DEFAULT 56;
