'use client';
import { LevelBadge } from '@/shared/ui/LevelBadge';
import { Dropdown } from '@/shared/ui/Dropdown';
import * as React from 'react';
import { PageHeader } from '@/shared/ui';
import { apiClient, ApiClientError } from '@/shared/api/api-client';

export default function LearnerGroupsPage(){
 const [groups,setGroups]=React.useState<any[]>([]),[goals,setGoals]=React.useState<any[]>([]),[learners,setLearners]=React.useState<any[]>([]); const [name,setName]=React.useState(''),[goalId,setGoalId]=React.useState(''),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [g,c,u]=await Promise.all([apiClient.get<any[]>('/learner-groups'),apiClient.get<any>('/career-goals'),apiClient.get<any>('/users?role=learner&limit=100')]);setGroups(g);setGoals(c.data??c??[]);setLearners(u.data??u??[]);}catch(e){setError(e instanceof ApiClientError?e.message:'Không thể tải nhóm học viên');}finally{setLoading(false)}},[]); React.useEffect(()=>{void load()},[load]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;try{await apiClient.post('/learner-groups',{name,careerGoalId:goalId||null});setName('');setGoalId('');await load()}catch(e){setError(e instanceof ApiClientError?e.message:'Không thể tạo nhóm')}};
 const add=async(groupId:string,learnerId:string)=>{if(!learnerId)return;try{await apiClient.post(`/learner-groups/${groupId}/members`,{learnerId});await load()}catch(e){setError(e instanceof ApiClientError?e.message:'Không thể thêm học viên')}};
 const remove=async(groupId:string,learnerId?:string)=>{try{await apiClient.delete(learnerId?`/learner-groups/${groupId}/members/${learnerId}`:`/learner-groups/${groupId}`);await load()}catch(e){setError(e instanceof ApiClientError?e.message:'Không thể cập nhật nhóm')}};
 return <div><PageHeader title="Phân nhóm học viên" description="Quản lý nhóm theo mục tiêu nghề nghiệp Cloud, Security, Data, BA và các hướng chuyên môn khác"/>{error&&<div className="mt-4 rounded-xl bg-error-container p-3 text-sm text-on-error-container">{error}</div>}<form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl border border-outline-variant bg-white p-5 md:grid-cols-[1fr_1fr_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Tên nhóm học viên" className="h-11 rounded-xl border border-outline-variant px-3"/><Dropdown value={goalId} onChange={e=>setGoalId(e.target.value)} className="h-11 rounded-xl border border-outline-variant px-3"><option value="">Chọn mục tiêu nghề nghiệp</option>{goals.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Dropdown><button className="h-11 rounded-xl bg-primary px-5 font-bold text-white">Tạo nhóm</button></form><div className="mt-5 grid gap-4 xl:grid-cols-2">{loading?<p>Đang tải...</p>:groups.map(group=><article key={group.id} className="rounded-2xl border border-outline-variant bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="text-lg font-bold">{group.name}</h2><p className="mt-1 text-sm text-on-surface-variant">{group.careerGoal?.name??'Chưa gắn mục tiêu nghề nghiệp'} · {group._count?.members??group.members?.length??0} học viên</p></div><button onClick={()=>window.confirm(`Bạn có muốn xóa nhóm “${group.name}” hay không?`)&&void remove(group.id)} className="text-error"><span className="material-symbols-outlined">delete</span></button></div><Dropdown defaultValue="" onChange={e=>{void add(group.id,e.target.value);e.currentTarget.value=''}} className="mt-4 h-10 w-full rounded-xl border border-outline-variant px-3 text-sm"><option value="">Thêm học viên vào nhóm...</option>{learners.filter(l=>!group.members?.some((m:any)=>m.learnerId===l.id)).map(l=><option key={l.id} value={l.id}>{l.userDetail?.displayName??l.email}</option>)}</Dropdown><div className="mt-3 divide-y divide-outline-variant/40">{group.members?.map((m:any)=><div key={m.learnerId} className="flex items-center justify-between py-2.5"><div><p className="text-sm font-semibold">{m.learner.userDetail?.displayName??m.learner.email}</p><LevelBadge level={m.learner.learnerProfile?.level} fallback="Chưa có trình độ" /></div><button onClick={()=>void remove(group.id,m.learnerId)} className="text-xs font-semibold text-error">Gỡ khỏi nhóm</button></div>)}{!group.members?.length&&<p className="py-4 text-sm text-on-surface-variant">Nhóm chưa có học viên.</p>}</div></article>)}</div></div>;
}
