import type { Translations } from './vi';

export const en: Translations = {
  common: {
    appName: 'TechEnglish Pro', search: 'Search courses...', loading: 'Loading...', error: 'An error occurred', retry: 'Retry', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', confirm: 'Confirm', back: 'Back', next: 'Next', submit: 'Submit', close: 'Close', seeAll: 'See all', learnMore: 'Learn more', noData: 'No data', signOut: 'Sign out', signIn: 'Sign in', signUp: 'Sign up', darkMode: 'Dark mode', lightMode: 'Light mode', language: 'Language', vietnamese: 'Tiếng Việt', english: 'English', minutes: 'minutes', hours: 'hours', days: 'days', weeks: 'weeks', free: 'Free', pro: 'PRO', new: 'New', popular: 'Popular', completed: 'Completed', inProgress: 'In progress', locked: 'Locked', start: 'Start', continue: 'Continue', finish: 'Finish', score: 'Score', level: 'Level', domain: 'Domain', all: 'All', filter: 'Filter', sort: 'Sort', copy: 'Copy', copied: 'Copied!', upgrade: 'Upgrade PRO', notLoggedIn: 'Not logged in', loginToUse: 'Please login to use this feature',
  },
  nav: {
    home: 'Home', learning: 'Learning', practice: 'Practice', progress: 'Progress', roadmap: 'Roadmap', achievements: 'Achievements', explore: 'Explore', profile: 'Profile', admin: 'Admin', planner: 'Study Planner', notifications: 'Notifications', analytics: 'Analytics', leaderboard: 'Leaderboard', career: 'Career Path', aiRecommendations: 'AI Recommendations', certifications: 'Certifications', saved: 'Saved Lessons', mockInterview: 'AI Mock Interview', writingPractice: 'AI Writing Practice', smartReview: 'AI Smart Review', readingLab: 'Technical Reading Lab', dictionary: 'Technical Dictionary', calendar: 'Calendar', community: 'Community', pathGenerator: 'Path Generator', skillGap: 'Skill Gap', examReadiness: 'Exam Readiness',
  },
  home: {
    greeting: 'Hello', greetingQuestion: 'What do you want to learn today?', subtitle: 'Continue your IT English journey.', level: 'Level', itField: 'IT Field', certGoal: 'Cert Goal', continueLearn: 'Continue learning', flashSale: 'Flash Sale', flashSaleActive: 'Flash Sale active', timeLeft: 'Time left', voucherSection: 'Applied vouchers', managedByAdmin: 'managed by Admin', copyCode: 'Copy code', minOrder: 'Min order', noLimit: 'No limit', discount: 'Discount', discoverFeatures: 'Discover features', featuredLessons: 'Featured lessons', streak: 'day streak', exp: 'EXP', todayGoal: 'Today goal', noActivePromo: 'No active promo', upgradePro: 'Upgrade to PRO!', upgradeDesc: 'Unlock all lessons, AI features, and unlimited exams.', viewPlans: 'View plans',
  },
  lessons: { title: 'Lessons', searchPlaceholder: 'Search lessons...', allDomains: 'All domains', allLevels: 'All levels', estimatedTime: 'Estimated time', startLesson: 'Start lesson', continueLesson: 'Continue lesson', proOnly: 'PRO only', noLessons: 'No lessons found.', vocabulary: 'Vocabulary', terms: 'terms', lessonComplete: 'Lesson completed', },
  profile: { title: 'Profile', editProfile: 'Edit profile', changePassword: 'Change password', activePlan: 'Active plan', learningHistory: 'Learning history', paymentHistory: 'Payment history', achievements: 'Achievements & Badges', displayName: 'Display name', email: 'Email', phone: 'Phone number', bio: 'Bio', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', passwordRequirements: 'Min 8 chars, uppercase, lowercase and number', saveChanges: 'Save changes', updatePassword: 'Update password', planExpires: 'Expires', noPlan: 'No active plan', viewPlans: 'View plans', monthPlan: 'months', noHistory: 'No learning history', noPayments: 'No payment history', noBadges: 'No achievements yet', keepLearning: 'Keep learning to unlock achievements!', signOutConfirm: 'Are you sure you want to sign out?', },
  practice: { title: 'Practice', exams: 'Exams', flashcards: 'Flashcards', scenario: 'Real-world scenario', startExam: 'Start exam', questions: 'questions', duration: 'Duration', difficulty: 'Difficulty', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', noExams: 'No exams found.', },
  analytics: { title: 'Learning Analytics', subtitle: 'Track your technical learning progress and performance.', totalExp: 'Total EXP', lessonsCompleted: 'Lessons completed', weeklyPoints: 'Weekly points', currentStreak: 'Current streak', days: 'days', progressByDomain: 'Progress by domain', recentActivity: 'Recent activity', noActivity: 'No activity yet.', weeklyProgress: 'Weekly progress', insights: 'Insights', insight1: 'You learn best in the morning (8:00 - 10:00).', insight2: 'Your favorite topic is Cloud Computing.', insight3: 'Your test scores have increased by 15% compared to last month.' },
  leaderboard: { title: 'Community Leaderboard', subtitle: 'Top performers in the TechEnglish community.', weekly: 'This week', monthly: 'This month', allTime: 'All time', rank: 'Rank', player: 'User', exp: 'Points', lessons: 'Lessons', streak: 'Streak', myRank: 'My rank', topLearners: 'Top learners', noData: 'No data yet.', checkIn: 'Check in today', checkedIn: 'Checked in', earnExp: 'Earn EXP', currentUserLabel: 'Current' },
  notifications: { title: 'Notifications', unread: 'unread', markAllRead: 'Mark all as read', markRead: 'Mark as read', noNotifications: 'No notifications.', allCaughtUp: 'You are all caught up!', },
  planner: { title: 'Study Planner', addPlan: 'Add plan', noPlan: 'No plans yet.', createFirst: 'Create your first plan!', lessonTitle: 'Lesson title', plannedDate: 'Planned date', duration: 'Duration (min)', note: 'Note', markDone: 'Mark as done', undone: 'Mark as undone', deletePlan: 'Delete plan', weekly: 'This week', today: 'Today', upcoming: 'Upcoming', overdue: 'Overdue', },
  career: { title: 'Career Path', marketInsights: 'Market insights', salaryTrend: 'Salary trend', topSkills: 'Top skills', jobOpenings: 'Job openings', certValue: 'Cert value', careerPath: 'Career roadmap', jobTitle: 'Job title', avgSalary: 'Avg salary', demand: 'Demand', high: 'High', medium: 'Medium', low: 'Low', startCareer: 'Start path', },
  achievements: { title: 'Achievements & Milestones', badges: 'Badges', milestones: 'Milestones', earned: 'Earned', locked: 'Locked', progress: 'Progress', totalBadges: 'Total badges', keepGoing: 'Keep going to unlock more!', noBadges: 'No badges yet.', },
  mockInterview: { title: 'AI Mock Interview', subtitle: 'Practice technical interviews with AI', chooseTopic: 'Choose topic', chooseDifficulty: 'Choose difficulty', start: 'Start interview', question: 'Question', of: 'of', yourAnswer: 'Your answer...', submit: 'Submit answer', aiFeedback: 'AI Feedback', nextQuestion: 'Next question', result: 'Interview result', finalScore: 'Final score', tryAgain: 'Try again', viewHistory: 'View history', history: 'Interview history', networking: 'Networking', cloud: 'Cloud Computing', security: 'Security', devops: 'DevOps', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', },
  writingPractice: { title: 'AI Writing Practice', subtitle: 'Practice technical English writing with AI feedback', choosePrompt: 'Choose prompt', prompt: 'Prompt', writeHere: 'Write here...', wordCount: 'words', submitWriting: 'Submit', submitting: 'Grading...', grammar: 'Grammar', clarity: 'Clarity', vocabulary: 'Vocabulary', overall: 'Overall score', aiFeedback: 'AI Feedback', history: 'Submission history', noHistory: 'No submissions yet.', writingTips: 'Writing tips', tabWrite: 'Write', tabHistory: 'History', },
  skillGap: { title: 'Skill Gap Analysis', subtitle: 'Compare your skills with target roles', targetRole: 'Target role', matchPercent: 'Match', currentLevel: 'Current', required: 'Required', needImprovement: 'Needs improvement', achieved: 'Achieved', priorityLearn: 'Priority to learn', learnNow: 'Learn now', proposedPath: 'Proposed path', estimatedTime: 'Estimated time', },
  examReadiness: { title: 'Exam Readiness Score', subtitle: 'Evaluate your readiness for certification exams', chooseExam: 'Choose target cert', readinessScore: 'Readiness score', strongAreas: 'Strong areas', weakAreas: 'Areas for improvement', studyPlan: 'Study plan', practiceNow: 'Practice now', estimatedReady: 'Estimated ready in', domainScores: 'Domain scores', },
  smartReview: { title: 'AI Smart Review', subtitle: 'Smart review with AI flashcards', reviewSession: 'Review session', cardOf: 'cards', clickToFlip: 'Click to flip', forgot: 'Forgot', almostGot: 'Almost got it', remembered: 'Remembered', sessionComplete: 'Review session complete!', reviewedToday: 'Reviewed today', memoryRate: 'Memory rate', filterByDomain: 'Filter by domain', startReview: 'Start review', },
  readingLab: { title: 'Technical Reading Lab', subtitle: 'Practice reading technical documents', selectLesson: 'Select lesson', readingSpeed: 'Reading speed', wpm: 'wpm', comprehension: 'Comprehension', checkAnswer: 'Check answer', correct: 'Correct', incorrect: 'Incorrect', allDomains: 'All domains', noSelection: 'Select a reading lesson from the left', startReading: 'Start reading', finishReading: 'Finish reading', },
  dictionary: { title: 'IT Technical Dictionary', subtitle: 'Look up IT terms', searchPlaceholder: 'Search IT terms...', wordOfDay: 'Word of the day', noResults: 'No words found.', tryOther: 'Try another word', pronunciation: 'Pronunciation', definition: 'Definition', example: 'Example', relatedWords: 'Related words', allLetters: 'All', },
  calendar: { title: 'Study Calendar', subtitle: 'Manage your study plans', addPlan: '+ Add plan', planned: 'planned', done: 'done', thisMonth: 'This month', upcomingWeek: 'Upcoming this week', noPlanDay: 'No plans for this day.', addForDay: 'Add plan for this day', lessonName: 'Lesson name', durationMin: 'Duration (min)', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun', },
  community: { title: 'TechEnglish Community', subtitle: 'Discuss and share IT knowledge', askQuestion: 'Ask a question', newPost: 'New post', postTitle: 'Post title', postContent: 'Content...', tags: 'Tags (comma separated)', submitPost: 'Submit post', votes: 'votes', comments: 'comments', comment: 'Comment', commentPlaceholder: 'Write a comment...', noComments: 'No comments yet.', noPosts: 'No posts yet.', pinned: 'Pinned', viewPost: 'View post', allTags: 'All', },
  roadmap: { title: 'Learning Roadmap', subtitle: 'Systematic IT English learning journey', currentPhase: 'Current phase', nextStep: 'Next step', completed: 'Completed', inProgress: 'In progress', upcoming: 'Upcoming', startLesson: 'Start lesson', phase: 'Phase', },
  certifications: { title: 'Certifications', subtitle: 'Track your IT certification progress', progress: 'Progress', enrolledCerts: 'Enrolled certs', allCerts: 'All certs', enroll: 'Enroll', viewDetails: 'View details', passed: 'Passed', inProgress: 'In progress', notStarted: 'Not started', lessons: 'lessons', exams: 'exams', },
  saved: { title: 'Saved Lessons', subtitle: 'Lessons you have bookmarked', noSaved: 'No saved lessons.', saveHint: 'Click 🔖 in a lesson to save.', remove: 'Remove', goLearn: 'Learn now', },
  pathGenerator: { title: 'Path Generator', subtitle: 'AI personalized learning path', goalLabel: 'Career goal', levelLabel: 'Current level', timePerDay: 'Time per day', generate: 'Generate path', generating: 'Generating...', resultTitle: 'Proposed Path', savePlan: 'Save plan', saved: 'Saved!', totalTime: 'Estimated total time', step: 'Step', learnNow: 'Learn now', estimatedWeeks: 'weeks', },
  aiRecommendations: { title: 'AI Recommendations', subtitle: 'Personalized lessons based on progress', forYou: 'For you', basedOnProgress: 'Based on learning progress', noRecommendations: 'No recommendations yet.', startLearning: 'Start learning to get recommendations!', learnNow: 'Learn now', recommended: 'Recommended', reason: 'Reason', },
} as any;



