import type { Translations } from './vi';

export const en: Translations = {
  common: {
    appName: 'TechEnglish Pro', search: 'Search courses...', loading: 'Loading...', error: 'An error occurred', retry: 'Retry', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', confirm: 'Confirm', back: 'Back', next: 'Next', submit: 'Submit', close: 'Close', seeAll: 'See all', learnMore: 'Learn more', noData: 'No data', signOut: 'Sign out', signIn: 'Sign in', signUp: 'Sign up', darkMode: 'Dark mode', lightMode: 'Light mode', language: 'Language', vietnamese: 'Tiếng Việt', english: 'English', minutes: 'minutes', hours: 'hours', days: 'days', weeks: 'weeks', free: 'Free', pro: 'PRO', new: 'New', popular: 'Popular', completed: 'Completed', inProgress: 'In progress', locked: 'Locked', start: 'Start', continue: 'Continue', finish: 'Finish', score: 'Score', level: 'Level', domain: 'Domain', all: 'All', filter: 'Filter', sort: 'Sort', copy: 'Copy', copied: 'Copied!', upgrade: 'Upgrade PRO', notLoggedIn: 'Not logged in', loginToUse: 'Please login to use this feature',
  },
  nav: {
    home: 'Home', learning: 'Learning', practice: 'Practice', progress: 'Progress', explore: 'Explore', profile: 'Profile', admin: 'Admin', planner: 'Study Planner', notifications: 'Notifications', career: 'Career Path', aiRecommendations: 'Study Suggestions', certifications: 'Certifications', mockInterview: 'Mock Interview', writingPractice: 'Technical Writing', readingLab: 'Technical Reading Lab', calendar: 'Calendar', community: 'Community', skillGap: 'Skill Gap',
  },
  home: {
    greeting: 'Hello', greetingQuestion: 'What do you want to learn today?', subtitle: 'Continue your IT English journey.', level: 'Level', itField: 'IT Field', certGoal: 'Cert Goal', continueLearn: 'Continue learning', discoverFeatures: 'Discover features', featuredLessons: 'Featured lessons', todayGoal: 'Today goal', upgradePro: 'Upgrade to PRO!', upgradeDesc: 'Unlock all lessons, AI features, and unlimited exams.', viewPlans: 'View plans',
  },
  lessons: { title: 'Lessons', searchPlaceholder: 'Search lessons...', allDomains: 'All domains', allLevels: 'All levels', estimatedTime: 'Estimated time', startLesson: 'Start lesson', continueLesson: 'Continue lesson', proOnly: 'PRO only', noLessons: 'No lessons found.', vocabulary: 'Vocabulary', terms: 'terms', lessonComplete: 'Lesson completed', },
  profile: { title: 'Profile', editProfile: 'Edit profile', changePassword: 'Change password', activePlan: 'Active plan', learningHistory: 'Learning history', paymentHistory: 'Payment history', displayName: 'Display name', email: 'Email', phone: 'Phone number', bio: 'Bio', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', passwordRequirements: 'Min 8 chars, uppercase, lowercase and number', saveChanges: 'Save changes', updatePassword: 'Update password', planExpires: 'Expires', noPlan: 'No active plan', viewPlans: 'View plans', monthPlan: 'months', noHistory: 'No learning history', noPayments: 'No payment history', signOutConfirm: 'Are you sure you want to sign out?', },
  practice: { title: 'Practice', exams: 'Exams', flashcards: 'Flashcards', scenario: 'Real-world scenario', startExam: 'Start exam', questions: 'questions', duration: 'Duration', difficulty: 'Difficulty', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', noExams: 'No exams found.', },
  notifications: { title: 'Notifications', unread: 'unread', markAllRead: 'Mark all as read', markRead: 'Mark as read', noNotifications: 'No notifications.', allCaughtUp: 'You are all caught up!', },
  planner: { title: 'Study Planner', addPlan: 'Add plan', noPlan: 'No plans yet.', createFirst: 'Create your first plan!', lessonTitle: 'Lesson title', plannedDate: 'Planned date', duration: 'Duration (min)', note: 'Note', markDone: 'Mark as done', undone: 'Mark as undone', deletePlan: 'Delete plan', weekly: 'This week', today: 'Today', upcoming: 'Upcoming', overdue: 'Overdue', },
  career: { title: 'Career Path', marketInsights: 'Market insights', salaryTrend: 'Salary trend', topSkills: 'Top skills', jobOpenings: 'Job openings', certValue: 'Cert value', careerPath: 'Career roadmap', jobTitle: 'Job title', avgSalary: 'Avg salary', demand: 'Demand', high: 'High', medium: 'Medium', low: 'Low', startCareer: 'Start path', },
  mockInterview: { title: 'Mock Interview', subtitle: 'Practice technical interviews with automatic scoring', chooseTopic: 'Choose topic', chooseDifficulty: 'Choose difficulty', start: 'Start interview', question: 'Question', of: 'of', yourAnswer: 'Your answer...', submit: 'Submit answer', aiFeedback: 'Automatic Feedback', nextQuestion: 'Next question', result: 'Interview result', finalScore: 'Final score', tryAgain: 'Try again', viewHistory: 'View history', history: 'Interview history', networking: 'Networking', cloud: 'Cloud Computing', security: 'Security', devops: 'DevOps', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', },
  writingPractice: { title: 'Technical Writing Practice', subtitle: 'Practice technical English with criteria-based scoring', choosePrompt: 'Choose prompt', prompt: 'Prompt', writeHere: 'Write here...', wordCount: 'words', submitWriting: 'Submit', submitting: 'Grading...', grammar: 'Grammar', clarity: 'Clarity', vocabulary: 'Vocabulary', overall: 'Overall score', aiFeedback: 'Automatic Feedback', history: 'Submission history', noHistory: 'No submissions yet.', writingTips: 'Writing tips', tabWrite: 'Write', tabHistory: 'History', },
  skillGap: { title: 'Skill Gap Analysis', subtitle: 'Compare your skills with target roles', targetRole: 'Target role', matchPercent: 'Match', currentLevel: 'Current', required: 'Required', needImprovement: 'Needs improvement', achieved: 'Achieved', priorityLearn: 'Priority to learn', learnNow: 'Learn now', proposedPath: 'Proposed path', estimatedTime: 'Estimated time', },
  readingLab: { title: 'Technical Reading Lab', subtitle: 'Practice reading technical documents', selectLesson: 'Select lesson', readingSpeed: 'Reading speed', wpm: 'wpm', comprehension: 'Comprehension', checkAnswer: 'Check answer', correct: 'Correct', incorrect: 'Incorrect', allDomains: 'All domains', noSelection: 'Select a reading lesson from the left', startReading: 'Start reading', finishReading: 'Finish reading', },
  calendar: { title: 'Study Calendar', subtitle: 'Manage your study plans', addPlan: '+ Add plan', planned: 'planned', done: 'done', thisMonth: 'This month', upcomingWeek: 'Upcoming this week', noPlanDay: 'No plans for this day.', addForDay: 'Add plan for this day', lessonName: 'Lesson name', durationMin: 'Duration (min)', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun', },
  community: { title: 'TechEnglish Community', subtitle: 'Discuss and share IT knowledge', askQuestion: 'Ask a question', newPost: 'New post', postTitle: 'Post title', postContent: 'Content...', tags: 'Tags (comma separated)', submitPost: 'Submit post', votes: 'votes', comments: 'comments', comment: 'Comment', commentPlaceholder: 'Write a comment...', noComments: 'No comments yet.', noPosts: 'No posts yet.', pinned: 'Pinned', viewPost: 'View post', allTags: 'All', },
  certifications: { title: 'Certifications', subtitle: 'Track your IT certification progress', progress: 'Progress', enrolledCerts: 'Enrolled certs', allCerts: 'All certs', enroll: 'Enroll', viewDetails: 'View details', passed: 'Passed', inProgress: 'In progress', notStarted: 'Not started', lessons: 'lessons', exams: 'exams', },
  aiRecommendations: { title: 'Study Suggestions', subtitle: 'Lessons ordered from your learning progress', forYou: 'For you', basedOnProgress: 'Based on learning progress', noRecommendations: 'No recommendations yet.', startLearning: 'Start learning to get recommendations!', learnNow: 'Learn now', recommended: 'Recommended', reason: 'Reason', },
} as any;



