export const vi = {
  common: {
    appName: 'TechEnglish Pro', search: 'Tìm kiếm khoá học...', loading: 'Đang tải...', error: 'Đã có lỗi xảy ra', retry: 'Thử lại', save: 'Lưu', cancel: 'Hủy', delete: 'Xóa', edit: 'Chỉnh sửa', confirm: 'Xác nhận', back: 'Quay lại', next: 'Tiếp theo', submit: 'Gửi', close: 'Đóng', seeAll: 'Xem tất cả', learnMore: 'Tìm hiểu thêm', noData: 'Không có dữ liệu', signOut: 'Đăng xuất', signIn: 'Đăng nhập', signUp: 'Đăng ký', darkMode: 'Chế độ tối', lightMode: 'Chế độ sáng', language: 'Ngôn ngữ', vietnamese: 'Tiếng Việt', english: 'English', minutes: 'phút', hours: 'giờ', days: 'ngày', weeks: 'tuần', months: 'tháng', free: 'Miễn phí', pro: 'PRO', new: 'Mới', popular: 'Phổ biến', completed: 'Hoàn thành', inProgress: 'Đang học', locked: 'Bị khóa', start: 'Bắt đầu', continue: 'Tiếp tục', finish: 'Hoàn thành', score: 'Điểm', level: 'Cấp độ', domain: 'Lĩnh vực', all: 'Tất cả', filter: 'Lọc', sort: 'Sắp xếp', copy: 'Sao chép', copied: 'Đã sao chép!', upgrade: 'Nâng cấp PRO', notLoggedIn: 'Bạn chưa đăng nhập', loginToUse: 'Vui lòng đăng nhập để sử dụng tính năng này',
  },
  nav: {
    home: 'Trang chủ', learning: 'Học tập', practice: 'Luyện tập', exams: 'Thi thử', progress: 'Tiến độ', explore: 'Khám phá', profile: 'Hồ sơ', admin: 'Quản trị', planner: 'Kế hoạch học tập', notifications: 'Thông báo', career: 'Định hướng sự nghiệp', aiRecommendations: 'Gợi ý học tập', certifications: 'Chứng chỉ', mockInterview: 'Phỏng vấn mô phỏng', writingPractice: 'Luyện viết kỹ thuật', readingLab: 'Technical Reading Lab', calendar: 'Lịch học', community: 'Cộng đồng', skillGap: 'Phân tích kỹ năng',
  },
  home: {
    greeting: 'Chào bạn', greetingQuestion: 'Hôm nay bạn muốn học gì?', subtitle: 'Tiếp tục hành trình chinh phục tiếng Anh IT của bạn.', level: 'Trình độ', itField: 'Lĩnh vực IT', certGoal: 'Mục tiêu chứng chỉ', continueLearn: 'Tiếp tục học ngay', startLearn: 'Bắt đầu học ngay', recommendedLessons: 'Bài học đề xuất', discoverFeatures: 'Khám phá tính năng', featuredLessons: 'Bài học nổi bật', todayGoal: 'Mục tiêu hôm nay', upgradePro: 'Nâng cấp PRO ngay!', upgradeDesc: 'Mở khóa toàn bộ bài học và đề thi không giới hạn.', viewPlans: 'Xem các gói',
  },
  lessons: { title: 'Bài học', searchPlaceholder: 'Tìm bài học...', allDomains: 'Tất cả lĩnh vực', allLevels: 'Tất cả cấp độ', estimatedTime: 'Thời gian ước tính', startLesson: 'Bắt đầu học', continueLesson: 'Tiếp tục học', reviewLesson: 'Ôn tập lại', proOnly: 'Chỉ PRO', noLessons: 'Không có bài học nào.', vocabulary: 'Từ vựng', terms: 'thuật ngữ', lessonComplete: 'Hoàn thành bài học', beginner: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', sortNewest: 'Mới nhất', sortOldest: 'Cũ nhất', sortProgress: 'Tiến độ', notStarted: 'Chưa học', completed: 'Đã hoàn thành', inProgress: 'Đang học', noResults: 'Không tìm thấy bài học nào phù hợp.', fetchError: 'Không thể tải danh sách bài học.', desc: 'Khám phá các bài học tiếng Anh chuyên ngành CNTT theo cấp độ và chủ đề.', prevSection: 'Phần trước', nextSection: 'Phần sau', },
  profile: { title: 'Hồ sơ cá nhân', editProfile: 'Chỉnh sửa thông tin', changePassword: 'Đổi mật khẩu', activePlan: 'Gói đang dùng', learningHistory: 'Lịch sử học tập', paymentHistory: 'Lịch sử thanh toán', displayName: 'Tên hiển thị', email: 'Email', phone: 'Số điện thoại', bio: 'Giới thiệu bản thân', currentPassword: 'Mật khẩu hiện tại', newPassword: 'Mật khẩu mới', confirmPassword: 'Xác nhận mật khẩu mới', passwordRequirements: 'Tối thiểu 8 ký tự, có chữ hoa, chữ thường và số', saveChanges: 'Lưu thay đổi', updatePassword: 'Cập nhật mật khẩu', planExpires: 'Hết hạn', noPlan: 'Chưa có gói nào', viewPlans: 'Xem gói học', monthPlan: 'tháng', noHistory: 'Chưa có lịch sử học tập', noPayments: 'Chưa có giao dịch', signOutConfirm: 'Bạn có chắc muốn đăng xuất?', },
  practice: { title: 'Luyện tập', exams: 'Bài kiểm tra', flashcards: 'Flashcards', startExam: 'Bắt đầu thi', questions: 'câu hỏi', duration: 'Thời gian', difficulty: 'Độ khó', beginner: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', noExams: 'Không có bài thi nào.', },
  notifications: { title: 'Thông báo', subtitle: 'Cập nhật tiến trình và hoạt động học tập của bạn.', unread: 'chưa đọc', markAllRead: 'Đánh dấu tất cả đã đọc', markRead: 'Đánh dấu đã đọc', noNotifications: 'Không có thông báo nào.', allCaughtUp: 'Bạn đã xem hết thông báo!', all: 'Tất cả', learning: 'Học tập', system: 'Hệ thống' },
  planner: { title: 'Kế hoạch học tập', subtitle: 'Kế hoạch học tập tuần này', weekSummary: 'Tổng quan tuần', estimatedHours: 'giờ dự kiến', recommended: 'Gợi ý cho bạn', addBtn: 'Thêm', addPlan: 'Thêm kế hoạch', noPlan: 'Chưa có kế hoạch nào.', createFirst: 'Tạo kế hoạch học tập đầu tiên!', lessonTitle: 'Tiêu đề bài học', plannedDate: 'Ngày học', duration: 'Thời gian (phút)', note: 'Ghi chú', markDone: 'Đánh dấu xong', undone: 'Bỏ đánh dấu', deletePlan: 'Xóa kế hoạch', weekly: 'Tuần này', today: 'Hôm nay', upcoming: 'Sắp tới', overdue: 'Quá hạn', mon: 'Thứ 2', tue: 'Thứ 3', wed: 'Thứ 4', thu: 'Thứ 5', fri: 'Thứ 6', sat: 'Thứ 7', sun: 'CN' },
  career: { title: 'Định hướng nghề nghiệp IT', subtitle: 'Phân tích chuyên sâu dựa trên lộ trình học tập và mục tiêu của bạn.', interestedDomain: 'Lĩnh vực quan tâm', interestLevel: 'Mức độ quan tâm', aiSuggestRole: 'Gợi ý nghề nghiệp theo hồ sơ', explore: 'Khám phá', certSuggest: 'Chứng chỉ đề xuất', details: 'Chi tiết', requiredSkills: 'Kỹ năng cần thiết', priorityTopics: 'Chủ đề học tập ưu tiên', jobDesc: 'Mô tả công việc và yêu cầu kỹ năng cho vị trí', examFee: 'Lệ phí thi', prepTime: 'Thời gian chuẩn bị', marketInsights: 'Thị trường việc làm', salaryTrend: 'Xu hướng lương', topSkills: 'Kỹ năng hot nhất', jobOpenings: 'Cơ hội việc làm', certValue: 'Giá trị chứng chỉ', careerPath: 'Lộ trình sự nghiệp', jobTitle: 'Vị trí công việc', avgSalary: 'Lương trung bình', demand: 'Nhu cầu', high: 'Cao', medium: 'Trung bình', low: 'Thấp', startCareer: 'Bắt đầu lộ trình', },
  mockInterview: { title: 'Phỏng vấn mô phỏng', subtitle: 'Luyện phỏng vấn kỹ thuật và nhận điểm tự động', chooseTopic: 'Chọn chủ đề phỏng vấn', chooseDifficulty: 'Chọn độ khó', start: 'Bắt đầu phỏng vấn', question: 'Câu hỏi', of: 'trong', yourAnswer: 'Câu trả lời của bạn...', submit: 'Nộp câu trả lời', aiFeedback: 'Nhận xét tự động', nextQuestion: 'Câu tiếp theo', result: 'Kết quả phỏng vấn', finalScore: 'Điểm tổng kết', tryAgain: 'Phỏng vấn lại', viewHistory: 'Xem lịch sử', history: 'Lịch sử phỏng vấn', networking: 'Networking', cloud: 'Cloud Computing', security: 'Bảo mật', devops: 'DevOps', beginner: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', },
  writingPractice: { title: 'Luyện viết kỹ thuật', subtitle: 'Luyện viết tiếng Anh kỹ thuật với cách chấm theo tiêu chí', choosePrompt: 'Chọn đề bài', prompt: 'Đề bài', writeHere: 'Viết bài của bạn ở đây...', wordCount: 'từ', submitWriting: 'Nộp bài', submitting: 'Đang chấm...', grammar: 'Ngữ pháp', clarity: 'Rõ ràng', vocabulary: 'Từ vựng', overall: 'Tổng điểm', aiFeedback: 'Nhận xét tự động', history: 'Lịch sử bài nộp', noHistory: 'Chưa nộp bài nào.', writingTips: 'Tips viết hiệu quả', tabWrite: 'Làm bài', tabHistory: 'Lịch sử', },
  skillGap: { title: 'Phân tích kỹ năng (Skill Gap)', subtitle: 'So sánh kỹ năng hiện tại với yêu cầu công việc mục tiêu', targetRole: 'Vị trí mục tiêu', matchPercent: 'Phù hợp', currentLevel: 'Hiện tại', required: 'Yêu cầu', needImprovement: 'Cần cải thiện', achieved: 'Đạt', priorityLearn: 'Ưu tiên học', learnNow: 'Học ngay', proposedPath: 'Lộ trình đề xuất', estimatedTime: 'Thời gian ước tính', },
  readingLab: { title: 'Technical Reading Lab', subtitle: 'Đọc hiểu tài liệu kỹ thuật tiếng Anh', selectLesson: 'Chọn bài đọc', readingSpeed: 'Tốc độ đọc', wpm: 'từ/phút', comprehension: 'Câu hỏi đọc hiểu', checkAnswer: 'Kiểm tra đáp án', correct: 'Đúng', incorrect: 'Sai', allDomains: 'Tất cả lĩnh vực', noSelection: 'Chọn bài đọc từ danh sách bên trái', startReading: 'Bắt đầu đọc', finishReading: 'Đã đọc xong', },
  calendar: { title: 'Lịch học', subtitle: 'Quản lý kế hoạch học tập theo lịch', addPlan: '+ Thêm kế hoạch', planned: 'bài đã lên kế hoạch', done: 'bài hoàn thành', thisMonth: 'Tháng này', upcomingWeek: 'Sắp tới trong tuần', noPlanDay: 'Không có kế hoạch cho ngày này.', addForDay: 'Thêm kế hoạch cho ngày này', lessonName: 'Tên bài học', durationMin: 'Thời lượng (phút)', mon: 'T2', tue: 'T3', wed: 'T4', thu: 'T5', fri: 'T6', sat: 'T7', sun: 'CN', },
  community: { title: 'Cộng đồng TechEnglish', subtitle: 'Thảo luận và chia sẻ kiến thức IT', askQuestion: 'Đặt câu hỏi', newPost: 'Bài viết mới', postTitle: 'Tiêu đề bài viết', postContent: 'Nội dung...', tags: 'Tags (phân cách bằng dấu phẩy)', submitPost: 'Đăng bài', votes: 'lượt thích', comments: 'bình luận', comment: 'Bình luận', commentPlaceholder: 'Viết bình luận...', noComments: 'Chưa có bình luận nào.', noPosts: 'Chưa có bài viết nào.', pinned: 'Ghim', viewPost: 'Xem bài viết', allTags: 'Tất cả', },
  certifications: { title: 'Chứng chỉ', subtitle: 'Theo dõi tiến độ học các chứng chỉ IT', progress: 'Tiến độ', enrolledCerts: 'Chứng chỉ đang học', allCerts: 'Tất cả chứng chỉ', enroll: 'Đăng ký học', viewDetails: 'Xem chi tiết', passed: 'Đã đạt', inProgress: 'Đang học', notStarted: 'Chưa bắt đầu', lessons: 'bài học', exams: 'bài thi', },
  aiRecommendations: { title: 'Gợi ý học tập', subtitle: 'Bài học được sắp xếp dựa trên tiến độ của bạn', forYou: 'Dành cho bạn', basedOnProgress: 'Dựa trên tiến độ học tập', noRecommendations: 'Chưa có gợi ý nào.', startLearning: 'Bắt đầu học để nhận gợi ý!', learnNow: 'Học ngay', recommended: 'Được gợi ý', reason: 'Lý do', },
};
export type Translations = typeof vi;

