export const vi = {
  common: {
    appName: 'TechEnglish Pro', search: 'Tìm kiếm khoá học...', loading: 'Đang tải...', error: 'Đã có lỗi xảy ra', retry: 'Thử lại', save: 'Lưu', cancel: 'Hủy', delete: 'Xóa', edit: 'Chỉnh sửa', confirm: 'Xác nhận', back: 'Quay lại', next: 'Tiếp theo', submit: 'Gửi', close: 'Đóng', seeAll: 'Xem tất cả', learnMore: 'Tìm hiểu thêm', noData: 'Không có dữ liệu', signOut: 'Đăng xuất', signIn: 'Đăng nhập', signUp: 'Đăng ký', darkMode: 'Chế độ tối', lightMode: 'Chế độ sáng', language: 'Ngôn ngữ', vietnamese: 'Tiếng Việt', english: 'English', minutes: 'phút', hours: 'giờ', days: 'ngày', weeks: 'tuần', months: 'tháng', free: 'Miễn phí', pro: 'PRO', new: 'Mới', popular: 'Phổ biến', completed: 'Hoàn thành', inProgress: 'Đang học', locked: 'Bị khóa', start: 'Bắt đầu', continue: 'Tiếp tục', finish: 'Hoàn thành', score: 'Điểm', level: 'Cấp độ', domain: 'Lĩnh vực', all: 'Tất cả', filter: 'Lọc', sort: 'Sắp xếp', copy: 'Sao chép', copied: 'Đã sao chép!', upgrade: 'Nâng cấp PRO', notLoggedIn: 'Bạn chưa đăng nhập', loginToUse: 'Vui lòng đăng nhập để sử dụng tính năng này',
  },
  nav: {
    home: 'Trang chủ', learning: 'Học tập', practice: 'Luyện tập', progress: 'Tiến độ', roadmap: 'Lộ trình', achievements: 'Thành tích', explore: 'Khám phá', profile: 'Hồ sơ', admin: 'Quản trị', planner: 'Kế hoạch học tập', notifications: 'Thông báo', analytics: 'Phân tích học tập', leaderboard: 'Bảng xếp hạng', career: 'Định hướng sự nghiệp', aiRecommendations: 'AI Gợi ý', certifications: 'Chứng chỉ', saved: 'Bài học đã lưu', mockInterview: 'AI Mock Interview', writingPractice: 'AI Writing Practice', smartReview: 'AI Smart Review', readingLab: 'Technical Reading Lab', dictionary: 'Từ điển kỹ thuật', calendar: 'Lịch học', community: 'Cộng đồng', pathGenerator: 'Tạo lộ trình', skillGap: 'Phân tích kỹ năng', examReadiness: 'Sẵn sàng thi',
  },
  home: {
    greeting: 'Chào bạn', greetingQuestion: 'Hôm nay bạn muốn học gì?', subtitle: 'Tiếp tục hành trình chinh phục tiếng Anh IT của bạn.', level: 'Trình độ', itField: 'Lĩnh vực IT', certGoal: 'Mục tiêu chứng chỉ', continueLearn: 'Tiếp tục học ngay', flashSale: 'Flash Sale', flashSaleActive: 'Flash Sale hoạt động', timeLeft: 'Thời gian còn lại', voucherSection: 'Mã giảm giá đang áp dụng', managedByAdmin: 'mã được quản lý bởi Admin', copyCode: 'Sao chép mã', minOrder: 'Đơn từ', noLimit: 'Không giới hạn', discount: 'Giảm', discoverFeatures: 'Khám phá tính năng', featuredLessons: 'Bài học nổi bật', streak: 'ngày học liên tiếp', exp: 'EXP', todayGoal: 'Mục tiêu hôm nay', noActivePromo: 'Không có khuyến mãi', upgradePro: 'Nâng cấp PRO ngay!', upgradeDesc: 'Mở khóa toàn bộ bài học, tính năng AI và đề thi không giới hạn.', viewPlans: 'Xem các gói',
  },
  lessons: { title: 'Bài học', searchPlaceholder: 'Tìm bài học...', allDomains: 'Tất cả lĩnh vực', allLevels: 'Tất cả cấp độ', estimatedTime: 'Thời gian ước tính', startLesson: 'Bắt đầu học', continueLesson: 'Tiếp tục học', proOnly: 'Chỉ PRO', noLessons: 'Không có bài học nào.', vocabulary: 'Từ vựng', terms: 'thuật ngữ', lessonComplete: 'Hoàn thành bài học', },
  profile: { title: 'Hồ sơ cá nhân', editProfile: 'Chỉnh sửa thông tin', changePassword: 'Đổi mật khẩu', activePlan: 'Gói đang dùng', learningHistory: 'Lịch sử học tập', paymentHistory: 'Lịch sử thanh toán', achievements: 'Thành tích & Badge', displayName: 'Tên hiển thị', email: 'Email', phone: 'Số điện thoại', bio: 'Giới thiệu bản thân', currentPassword: 'Mật khẩu hiện tại', newPassword: 'Mật khẩu mới', confirmPassword: 'Xác nhận mật khẩu mới', passwordRequirements: 'Tối thiểu 8 ký tự, có chữ hoa, chữ thường và số', saveChanges: 'Lưu thay đổi', updatePassword: 'Cập nhật mật khẩu', planExpires: 'Hết hạn', noPlan: 'Chưa có gói nào', viewPlans: 'Xem gói học', monthPlan: 'tháng', noHistory: 'Chưa có lịch sử học tập', noPayments: 'Chưa có giao dịch', noBadges: 'Chưa có thành tích nào', keepLearning: 'Tiếp tục học để mở khóa thành tích!', signOutConfirm: 'Bạn có chắc muốn đăng xuất?', },
  practice: { title: 'Luyện tập', exams: 'Bài kiểm tra', flashcards: 'Flashcards', scenario: 'Tình huống thực tế', startExam: 'Bắt đầu thi', questions: 'câu hỏi', duration: 'Thời gian', difficulty: 'Độ khó', beginner: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', noExams: 'Không có bài thi nào.', },
  analytics: { title: 'Phân tích học tập', subtitle: 'Theo dõi tiến độ và hiệu suất học tập kỹ thuật của bạn.', totalExp: 'Tổng EXP', lessonsCompleted: 'Bài đã hoàn thành', weeklyPoints: 'Điểm tuần này', currentStreak: 'Chuỗi ngày học', days: 'ngày', progressByDomain: 'Hiệu suất theo chủ đề', recentActivity: 'Hoạt động gần đây', noActivity: 'Chưa có hoạt động nào.', weeklyProgress: 'Mức độ hoạt động tuần này', insights: 'Phân tích', insight1: 'Bạn học hiệu quả nhất vào buổi sáng (8:00 - 10:00).', insight2: 'Chủ đề yêu thích của bạn là Cloud Computing.', insight3: 'Điểm kiểm tra của bạn đã tăng 15% so với tháng trước.' },
  leaderboard: { title: 'Bảng xếp hạng cộng đồng', subtitle: 'Top performers trong cộng đồng TechEnglish.', weekly: 'Tuần này', monthly: 'Tháng này', allTime: 'Mọi thời đại', rank: 'Rank', player: 'User', exp: 'Points', lessons: 'Lessons', streak: 'Streak', myRank: 'Thứ hạng của tôi', topLearners: 'Top người học', noData: 'Chưa có dữ liệu.', checkIn: 'Điểm danh hôm nay', checkedIn: 'Đã điểm danh', earnExp: 'Nhận EXP', currentUserLabel: 'Current' },
  notifications: { title: 'Thông báo', subtitle: 'Cập nhật tiến trình và hoạt động học tập của bạn.', unread: 'chưa đọc', markAllRead: 'Đánh dấu tất cả đã đọc', markRead: 'Đánh dấu đã đọc', noNotifications: 'Không có thông báo nào.', allCaughtUp: 'Bạn đã xem hết thông báo!', all: 'Tất cả', learning: 'Học tập', system: 'Hệ thống' },
  planner: { title: 'Kế hoạch học tập', subtitle: 'Kế hoạch học tập tuần này', weekSummary: 'Tổng quan tuần', estimatedHours: 'giờ dự kiến', streakAlert: 'Chuỗi 5 ngày học liên tiếp!', recommended: 'Gợi ý cho bạn', addBtn: 'Thêm', addPlan: 'Thêm kế hoạch', noPlan: 'Chưa có kế hoạch nào.', createFirst: 'Tạo kế hoạch học tập đầu tiên!', lessonTitle: 'Tiêu đề bài học', plannedDate: 'Ngày học', duration: 'Thời gian (phút)', note: 'Ghi chú', markDone: 'Đánh dấu xong', undone: 'Bỏ đánh dấu', deletePlan: 'Xóa kế hoạch', weekly: 'Tuần này', today: 'Hôm nay', upcoming: 'Sắp tới', overdue: 'Quá hạn', mon: 'Thứ 2', tue: 'Thứ 3', wed: 'Thứ 4', thu: 'Thứ 5', fri: 'Thứ 6', sat: 'Thứ 7', sun: 'CN' },
  career: { title: 'Định hướng nghề nghiệp IT', subtitle: 'Phân tích chuyên sâu dựa trên lộ trình học tập và mục tiêu của bạn.', interestedDomain: 'Lĩnh vực quan tâm', interestLevel: 'Mức độ quan tâm', aiSuggestRole: 'Gợi ý nghề nghiệp từ AI', explore: 'Khám phá', certSuggest: 'Chứng chỉ đề xuất', details: 'Chi tiết', requiredSkills: 'Kỹ năng cần thiết', priorityTopics: 'Chủ đề học tập ưu tiên', jobDesc: 'Mô tả công việc và yêu cầu kỹ năng cho vị trí', examFee: 'Lệ phí thi', prepTime: 'Thời gian chuẩn bị', marketInsights: 'Thị trường việc làm', salaryTrend: 'Xu hướng lương', topSkills: 'Kỹ năng hot nhất', jobOpenings: 'Cơ hội việc làm', certValue: 'Giá trị chứng chỉ', careerPath: 'Lộ trình sự nghiệp', jobTitle: 'Vị trí công việc', avgSalary: 'Lương trung bình', demand: 'Nhu cầu', high: 'Cao', medium: 'Trung bình', low: 'Thấp', startCareer: 'Bắt đầu lộ trình', },
  achievements: { title: 'Thành tích & Cột mốc', subtitle: 'Theo dõi tiến độ và các cột mốc học tập của bạn.', streakTitle: 'Learning Streak', streakSubtitle: 'Giữ vững phong độ học tập mỗi ngày.', streakDays: 'Ngày liên tiếp', milestonesTitle: 'Cột mốc thành tích', earnedBadgesTitle: 'Thành tích đạt được', badges: 'Huy hiệu', milestones: 'Mốc thành tích', earned: 'Đã đạt', locked: 'Chưa mở khóa', progress: 'Tiến độ', totalBadges: 'Tổng huy hiệu', keepGoing: 'Tiếp tục học để mở khóa thêm!', noBadges: 'Chưa có huy hiệu nào.', },
  roadmap: { title: 'Lộ trình học tập', subtitle: 'Theo dõi và tiếp tục lộ trình của bạn', progressOverview: 'Tiến độ tổng quan', completedLessons: 'Đã hoàn thành', lessons: 'bài học', all: 'Tất cả', basic: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', startNow: 'Học ngay', completed: 'Đã hoàn thành', locked: 'Khóa', currentPhase: 'Giai đoạn hiện tại', nextStep: 'Bước tiếp theo', inProgress: 'Đang thực hiện', upcoming: 'Sắp tới', startLesson: 'Bắt đầu học', phase: 'Giai đoạn', },
  mockInterview: { title: 'AI Mock Interview', subtitle: 'Luyện phỏng vấn kỹ thuật với AI', chooseTopic: 'Chọn chủ đề phỏng vấn', chooseDifficulty: 'Chọn độ khó', start: 'Bắt đầu phỏng vấn', question: 'Câu hỏi', of: 'trong', yourAnswer: 'Câu trả lời của bạn...', submit: 'Nộp câu trả lời', aiFeedback: 'Phản hồi từ AI', nextQuestion: 'Câu tiếp theo', result: 'Kết quả phỏng vấn', finalScore: 'Điểm tổng kết', tryAgain: 'Phỏng vấn lại', viewHistory: 'Xem lịch sử', history: 'Lịch sử phỏng vấn', networking: 'Networking', cloud: 'Cloud Computing', security: 'Bảo mật', devops: 'DevOps', beginner: 'Cơ bản', intermediate: 'Trung cấp', advanced: 'Nâng cao', },
  writingPractice: { title: 'AI Writing Practice', subtitle: 'Luyện viết tiếng Anh kỹ thuật với phản hồi AI', choosePrompt: 'Chọn đề bài', prompt: 'Đề bài', writeHere: 'Viết bài của bạn ở đây...', wordCount: 'từ', submitWriting: 'Nộp bài', submitting: 'Đang chấm...', grammar: 'Ngữ pháp', clarity: 'Rõ ràng', vocabulary: 'Từ vựng', overall: 'Tổng điểm', aiFeedback: 'Nhận xét của AI', history: 'Lịch sử bài nộp', noHistory: 'Chưa nộp bài nào.', writingTips: 'Tips viết hiệu quả', tabWrite: 'Làm bài', tabHistory: 'Lịch sử', },
  skillGap: { title: 'Phân tích kỹ năng (Skill Gap)', subtitle: 'So sánh kỹ năng hiện tại với yêu cầu công việc mục tiêu', targetRole: 'Vị trí mục tiêu', matchPercent: 'Phù hợp', currentLevel: 'Hiện tại', required: 'Yêu cầu', needImprovement: 'Cần cải thiện', achieved: 'Đạt', priorityLearn: 'Ưu tiên học', learnNow: 'Học ngay', proposedPath: 'Lộ trình đề xuất', estimatedTime: 'Thời gian ước tính', },
  examReadiness: { title: 'Điểm sẵn sàng thi', subtitle: 'Đánh giá mức độ sẵn sàng cho kỳ thi chứng chỉ', chooseExam: 'Chọn chứng chỉ mục tiêu', readinessScore: 'Điểm sẵn sàng', strongAreas: 'Điểm mạnh', weakAreas: 'Cần cải thiện', studyPlan: 'Kế hoạch ôn tập', practiceNow: 'Luyện thi ngay', estimatedReady: 'Ước tính sẵn sàng sau', domainScores: 'Điểm theo lĩnh vực', },
  smartReview: { title: 'AI Smart Review', subtitle: 'Ôn tập thông minh bằng flashcard AI', reviewSession: 'Phiên ôn tập', cardOf: 'thẻ', clickToFlip: 'Nhấn để lật thẻ', forgot: 'Không nhớ', almostGot: 'Gần được', remembered: 'Nhớ rồi', sessionComplete: 'Hoàn thành phiên ôn tập!', reviewedToday: 'Đã ôn hôm nay', memoryRate: 'Tỉ lệ nhớ', filterByDomain: 'Lọc theo lĩnh vực', startReview: 'Bắt đầu ôn tập', },
  readingLab: { title: 'Technical Reading Lab', subtitle: 'Đọc hiểu tài liệu kỹ thuật tiếng Anh', selectLesson: 'Chọn bài đọc', readingSpeed: 'Tốc độ đọc', wpm: 'từ/phút', comprehension: 'Câu hỏi đọc hiểu', checkAnswer: 'Kiểm tra đáp án', correct: 'Đúng', incorrect: 'Sai', allDomains: 'Tất cả lĩnh vực', noSelection: 'Chọn bài đọc từ danh sách bên trái', startReading: 'Bắt đầu đọc', finishReading: 'Đã đọc xong', },
  dictionary: { title: 'Từ điển kỹ thuật IT', subtitle: 'Tra cứu thuật ngữ IT chuyên ngành', searchPlaceholder: 'Tìm thuật ngữ kỹ thuật IT...', wordOfDay: 'Từ của ngày hôm nay', noResults: 'Không tìm thấy từ nào.', tryOther: 'Thử tìm từ khác', pronunciation: 'Phát âm', definition: 'Định nghĩa', example: 'Ví dụ', relatedWords: 'Từ liên quan', allLetters: 'Tất cả', },
  calendar: { title: 'Lịch học', subtitle: 'Quản lý kế hoạch học tập theo lịch', addPlan: '+ Thêm kế hoạch', planned: 'bài đã lên kế hoạch', done: 'bài hoàn thành', thisMonth: 'Tháng này', upcomingWeek: 'Sắp tới trong tuần', noPlanDay: 'Không có kế hoạch cho ngày này.', addForDay: 'Thêm kế hoạch cho ngày này', lessonName: 'Tên bài học', durationMin: 'Thời lượng (phút)', mon: 'T2', tue: 'T3', wed: 'T4', thu: 'T5', fri: 'T6', sat: 'T7', sun: 'CN', },
  community: { title: 'Cộng đồng TechEnglish', subtitle: 'Thảo luận và chia sẻ kiến thức IT', askQuestion: 'Đặt câu hỏi', newPost: 'Bài viết mới', postTitle: 'Tiêu đề bài viết', postContent: 'Nội dung...', tags: 'Tags (phân cách bằng dấu phẩy)', submitPost: 'Đăng bài', votes: 'lượt thích', comments: 'bình luận', comment: 'Bình luận', commentPlaceholder: 'Viết bình luận...', noComments: 'Chưa có bình luận nào.', noPosts: 'Chưa có bài viết nào.', pinned: 'Ghim', viewPost: 'Xem bài viết', allTags: 'Tất cả', },
  certifications: { title: 'Chứng chỉ', subtitle: 'Theo dõi tiến độ học các chứng chỉ IT', progress: 'Tiến độ', enrolledCerts: 'Chứng chỉ đang học', allCerts: 'Tất cả chứng chỉ', enroll: 'Đăng ký học', viewDetails: 'Xem chi tiết', passed: 'Đã đạt', inProgress: 'Đang học', notStarted: 'Chưa bắt đầu', lessons: 'bài học', exams: 'bài thi', },
  saved: { title: 'Bài học đã lưu', subtitle: 'Những bài học bạn đã bookmark', noSaved: 'Chưa lưu bài học nào.', saveHint: 'Nhấn vào biểu tượng 🔖 trong bài học để lưu.', remove: 'Bỏ lưu', goLearn: 'Học ngay', },
  pathGenerator: { title: 'Tạo lộ trình học tập', subtitle: 'AI tạo lộ trình học cá nhân hóa cho bạn', goalLabel: 'Mục tiêu nghề nghiệp', levelLabel: 'Trình độ hiện tại', timePerDay: 'Thời gian học/ngày', generate: 'Tạo lộ trình', generating: 'Đang tạo...', resultTitle: 'Lộ trình được đề xuất', savePlan: 'Lưu vào kế hoạch', saved: 'Đã lưu!', totalTime: 'Tổng thời gian ước tính', step: 'Bước', learnNow: 'Học ngay', estimatedWeeks: 'tuần', },
  aiRecommendations: { title: 'AI Gợi ý học tập', subtitle: 'Bài học được cá nhân hóa dựa trên tiến độ của bạn', forYou: 'Dành cho bạn', basedOnProgress: 'Dựa trên tiến độ học tập', noRecommendations: 'Chưa có gợi ý nào.', startLearning: 'Bắt đầu học để nhận gợi ý!', learnNow: 'Học ngay', recommended: 'Được gợi ý', reason: 'Lý do', },
};
export type Translations = typeof vi;

