import { useCallback, useEffect, useState } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import { api } from '../../src/shared/api/api-client';
import { useTheme } from '../../src/shared/store/theme-context';
import { FeatureScreen, featureStyles as s } from '../../src/shared/ui/FeatureScreen';

export default function AnalyticsScreen() {
  const { colors } = useTheme(); const [period, setPeriod] = useState('week'); const [overview, setOverview] = useState<any>({}); const [trend, setTrend] = useState<any[]>([]); const [hours, setHours] = useState<any>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [a, b, c]: any[] = await Promise.all([api.get('/analytics/sessions/overview'), api.get(`/analytics/sessions/trend?period=${period}`), api.get('/analytics/sessions/active-hours')]); setOverview(a.data ?? a); setTrend(b.data ?? b ?? []); setHours(c.data ?? c); setError(''); } catch (e: any) { setError(e.message || 'Không thể tải phân tích học tập.'); } finally { setLoading(false); } }, [period]); useEffect(() => { load(); }, [load]);
  const max = Math.max(1, ...trend.map(x => Number(x.hours) || 0));
  return <FeatureScreen title="Phân tích học tập" subtitle="Dữ liệu từ các phiên học thực tế" loading={loading} error={error} onRetry={load}><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{[['Tổng thời gian', overview.totalTimeFormatted], ['Trung bình/ngày', overview.avgTimePerDayFormatted], ['Chuỗi hiện tại', `${overview.currentStreakDays ?? 0} ngày`], ['Bài đã xong', overview.completedLessonsCount ?? 0]].map(([label, value]) => <View key={String(label)} style={[s.card, { width: '48%', backgroundColor: colors.surface, borderColor: colors.outlineVariant }]}><Text style={[s.muted, { color: colors.onSurfaceVariant }]}>{label}</Text><Text style={{ fontSize: 22, fontWeight: '900', color: colors.primary, marginTop: 5 }}>{String(value ?? 0)}</Text></View>)}</View><View style={[s.row, { marginVertical: 12 }]}>{[['week', '7 ngày'], ['month', '30 ngày'], ['year', '1 năm']].map(([key, label]) => <TouchableOpacity key={key} onPress={() => setPeriod(key)} style={[s.chip, { backgroundColor: period === key ? colors.primary : colors.surface }]}><Text style={{ color: period === key ? '#fff' : colors.onSurface }}>{label}</Text></TouchableOpacity>)}</View><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.outlineVariant }]}><Text style={[s.cardTitle, { color: colors.onSurface }]}>Xu hướng thời gian học</Text>{trend.map(item => <View key={item.date} style={[s.row, { marginTop: 9 }]}><Text style={{ width: 48, color: colors.onSurfaceVariant, fontSize: 11 }}>{item.dayLabel}</Text><View style={{ flex: 1, height: 10, backgroundColor: colors.outlineVariant, borderRadius: 9 }}><View style={{ width: `${Math.max(3, (Number(item.hours) / max) * 100)}%`, height: 10, backgroundColor: colors.primary, borderRadius: 9 }} /></View><Text style={{ width: 38, color: colors.onSurface, fontSize: 11 }}>{item.hours}h</Text></View>)}</View><View style={[s.card, { backgroundColor: `${colors.primary}12`, borderColor: colors.primary }]}><Text style={[s.cardTitle, { color: colors.onSurface }]}>Nhận xét</Text><Text style={[s.muted, { color: colors.onSurfaceVariant }]}>{hours.aiInsight}</Text></View></FeatureScreen>;
}
